version: "3.1"
services:

  webserver:
    image: nginx:latest
    container_name: ${PROJECT}-webserver
    working_dir: /application
    volumes:
    - .:/application
    - ./phpdocker/nginx/default.conf:/etc/nginx/includes.d/default.conf
    - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

    ports:
    - "8080:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: ${PROJECT}-php
    working_dir: /application
    volumes:
    - .:/application
    - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT}-mysql
    working_dir: /application
    volumes:
    - .:/application
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASS}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
    - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: ${PROJECT}-elastic
    working_dir: /application
    volumes:
    - .:/application
    ports:
    - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: ${PROJECT}-kibana
    working_dir: /application
    volumes:
    - .:/application
    ports:
    - "5601:5601"


